package entity;
// Generated Feb 7, 2020, 11:04:24 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapter generated by hbm2java
 */
@Entity(name = "chapter")
@Table(name = "chapter", catalog = "jwat")
public class Chapter implements java.io.Serializable {

	private int id;
	private String name;
	private Integer time;
	private Set<Lesson> lessons = new HashSet<Lesson>(0);

	public Chapter() {
	}

	public Chapter(int id) {
		this.id = id;
	}

	public Chapter(int id, String name, Integer time, Set<Lesson> lessons) {
		this.id = id;
		this.name = name;
		this.time = time;
		this.lessons = lessons;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "time")
	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chapter")
	public Set<Lesson> getLessons() {
		return this.lessons;
	}

	public void setLessons(Set<Lesson> lessons) {
		this.lessons = lessons;
	}

}
