package entity;
// Generated Feb 7, 2020, 11:04:24 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity(name = "notification")
@Table(name = "notification", catalog = "jwat")
public class Notification implements java.io.Serializable {

	private int id;
	private String title;
	private String content;
	private Boolean isRegister;

	public Notification() {
	}

	public Notification(int id) {
		this.id = id;
	}

	public Notification(int id, String title, String content, Boolean isRegister) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.isRegister = isRegister;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "is_register")
	public Boolean getIsRegister() {
		return this.isRegister;
	}

	public void setIsRegister(Boolean isRegister) {
		this.isRegister = isRegister;
	}

}
