package entity;
// Generated Feb 4, 2020, 5:29:55 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegistrationId generated by hbm2java
 */
@Embeddable
public class RegistrationId implements java.io.Serializable {

	private int idUser;
	private Date date;

	public RegistrationId() {
	}

	public RegistrationId(int idUser, Date date) {
		this.idUser = idUser;
		this.date = date;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegistrationId))
			return false;
		RegistrationId castOther = (RegistrationId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
