package entity;
// Generated Feb 7, 2020, 11:04:24 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Registration generated by hbm2java
 */
@Entity(name = "registration")
@Table(name = "registration", catalog = "jwat")
public class Registration implements java.io.Serializable {

	private RegistrationId id;
	private Users users;
	private Boolean morning;
	private Boolean afternoon;

	public Registration() {
	}

	public Registration(RegistrationId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public Registration(RegistrationId id, Users users, Boolean morning, Boolean afternoon) {
		this.id = id;
		this.users = users;
		this.morning = morning;
		this.afternoon = afternoon;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false, length = 100)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 19)) })
	public RegistrationId getId() {
		return this.id;
	}

	public void setId(RegistrationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "morning")
	public Boolean getMorning() {
		return this.morning;
	}

	public void setMorning(Boolean morning) {
		this.morning = morning;
	}

	@Column(name = "afternoon")
	public Boolean getAfternoon() {
		return this.afternoon;
	}

	public void setAfternoon(Boolean afternoon) {
		this.afternoon = afternoon;
	}

}
